### ISSUE TITLE
Bad state: Cannot add new events after calling close

### ISSUE THREAD

**Issue by MohiuddinM** [ReactiveX/rxdart#430]
When I create a new BehaviourSubject then everything works fine, but the problem occurrs when I close a stream:
`_streamController.close();`

The following code throws an exception:
```
while (_status == Status.running) {
  if (!_streamController.isClosed) {
    _streamController?.add(await _result());  // this line
  }
  await Future.delayed(interval);
}
```
```
I/flutter (32321): Bad state: Cannot add new events after calling close
I/flutter (32321): #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:251:24)
I/flutter (32321): #1      Subject._add (package:rxdart/src/subjects/subject.dart:135:17)
I/flutter (32321): #2      Subject.add (package:rxdart/src/subjects/subject.dart:129:5)
```

**Comment by frankpepermans** [comment]
You await a result, my guess is that your subject closes while this await is taking place.

It's best to first await the result, then do an isClosed check before adding.

**Comment by MohiuddinM** [comment]
Thank you for your feedback. This was the issue.
