### ISSUE TITLE
Broken debounceTime and sampleTime in Version 0.24.0 

### ISSUE THREAD

**Issue by KarimAbdo** [ReactiveX/rxdart#462]
On version 0.22.4 

```
BehaviorSubject _reports = BehaviorSubject<BuiltList<PetAlertReport>>();
Stream get reportStream$ => this._reports.stream;

...
_reportService.reportStream$.debounceTime(Duration(seconds: 1)).listen((reports) {
    ...
});
```
And similarly 
```
centerOfTheMap.sampleTime(Duration(seconds: 1)).listen((position) async {
      ...
});
```

also tried `...debounce((_) => TimerStream(true, Duration(seconds: 1)))...`
Were working as expected, but since I updated to 0.24.0 I started getting this errors:

```
I/flutter (14655): runtimetype of stream 1 Instance of 'BehaviorSubject<BuiltList<PetAlertReport>>'
I/flutter (14655): Caught error: type 'DebounceStreamTransformer<dynamic>' is not a subtype of type 'StreamTransformer<BuiltList<PetAlertReport>, dynamic>' of 'streamTransformer'
I/flutter (14655): #0      Stream.transform (dart:async/stream.dart)
I/flutter (14655): #1      DebounceExtensions.debounceTime (package:rxdart/src/transformers/backpressure/debounce.dart:80:48)
I/flutter (14655): #2      ToxicBaitMapViewModel.init (package:PetLEO/app/ui/03-toxic-baits/toxic-bait-map/new/toxic-bait-map-viewmodel.dart:65:87)
I/flutter (14655): #3      _rootRunUnary (dart:async/zone.dart:1192:38)
I/flutter (14655): #4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
I/flutter (14655): #5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
I/flutter (14655): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
I/flutter (14655): #7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
I/flutter (14655): #8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
I/flutter (14655): #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
I/flutter (14655): #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
```

and 

```
I/flutter (14655): Caught error: type 'SampleStreamTransformer<dynamic>' is not a subtype of type 'StreamTransformer<LatLng, dynamic>' of 'streamTransformer'
I/flutter (14655): #0      Stream.transform (dart:async/stream.dart)
I/flutter (14655): #1      SampleExtensions.sample (package:rxdart/src/transformers/backpressure/sample.dart:39:7)
I/flutter (14655): #2      SampleExtensions.sampleTime (package:rxdart/src/transformers/backpressure/sample.dart:51:7)
I/flutter (14655): #3      ToxicBaitMapViewModel.getAllBaitReports (package:PetLEO/app/ui/03-toxic-baits/toxic-bait-map/new/toxic-bait-map-viewmodel.dart:83:20)
I/flutter (14655): #4      ToxicBaitMapViewModel.init (package:PetLEO/app/ui/03-toxic-baits/toxic-bait-map/new/toxic-bait-map-viewmodel.dart:55:5)
I/flutter (14655): <asynchronous suspension>
I/flutter (14655): #5      new ToxicBaitMapViewModel (package:PetLEO/app/ui/03-toxic-baits/toxic-bait-map/new/toxic-bait-map-viewmodel.dart:50:5)
I/flutter (14655): #6      new _BaitMapState (package:PetLEO/app/ui/03-toxic-baits/toxic-bait-map/new/bait-map.dart:42:38)
I/flutter (14655): #7      BaitMap.createState (package:PetLEO/app/ui/03-toxic-baits/toxic-bait-map/new/bait-map.dart:37:34)
I/flutter (14655): #8      new StatefulElement (package:flutter/src/widgets/framework.dart:4591:25)
I/flutter (14655): #9      StatefulWidget.createElement (package:flutter/src/widge
```

**Comment by frankpepermans** [comment]
I think your getter is wrong, it should be:

Stream<BuiltList<Pet...>> get ...

**Comment by KarimAbdo** [comment]
@frankpepermans  Thank you. That actually solved it 👍 👍
